### ISSUE TITLE
[ui-upgrade]: Add number Validation to Form (Contact)

### ISSUE THREAD

**Issue by suyogschavan** [SyedImtiyaz-1/PreciousServices-#108]
**The contact form doesn't have validation**
The form is accepting any string value as a in the contact form. (This is my first time participating in Hacktoberfest)
The limit for mobile number should be 12 numbers. Not greater than 12 and less than 10.

**To Reproduce**
1. Go to 'Home Page'
2. Click on 'Contact' in Navbar
3. Enter any keywords (string).
4. fill all the other info
5. click on Submit

**Expected behavior**
'Invalid Email address' alert should be displayed if there's no @ sign present and it shouldn't get accepted after clicking on submit.

**Screenshots**
![Screenshot 2023-10-01 at 7 29 56 PM](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/83905525/db945372-2656-40d4-afd8-f0e7e4b430b5)

**Additional context**
I would like to contribute to this issue under **Hacktoberfest2023**

- [x] I want to work on this issue under the hacktoberfest2023

**Comment by suyogschavan** [comment]
Please assign me this

**Comment by SyedImtiyaz-1** [comment]
It's added by someone but please set limit for numbers its accepting number < 10 so it's must accept 12 nunber not greater than 12 and less than 10 okay and if there is no @ in email than show pop up for @ so please do this changes, and please let me know if you can do this or not.

**Comment by suyogschavan** [comment]
Yes I can do that. Please assign me this

**Comment by trana5197** [comment]
Hi, I am very interested in working on this assignment. Can you please assign it to me? I look forward to contributing to this project. Thank you!

**Comment by suyogschavan** [comment]
@trana5197 I am already working on this issue

**Comment by trana5197** [comment]
@suyogschavan  My bad. Go ahead

**Comment by suyogschavan** [comment]
Hey, @SyedImtiyaz-1 I am waiting to get assigned.

**Comment by SyedImtiyaz-1** [comment]
@suyogschavan Thanks for remainder.
