### ISSUE TITLE
[BUG]: Page Stuck Issue in the Project Section

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/PreciousServices-#122]
**Describe the bug**

**To Reproduce**
1. Go to 'Projects'
2. Click on 'Eye button of any project'
3. Scroll down to 'Click on close button [x-icon]'
4. See error : The page will get stuck now, it will only work after refresh.

**Expected behavior**
It should work smoothly after taping on the close button [x-icon] 

**Screenshots**
[Screencast from 02-10-23 12:23:27 AM IST.webm](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/121503426/ae999f30-9e75-4955-b442-e739baccb983)

- Watch this above video.

- **Note**: It's Urgent !!!

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by Ryan-Maddock-96** [comment]
Hello! Can I take this issue please? I can see what's breaking it

**Comment by SyedImtiyaz-1** [comment]
Please check it and let me know then I'll assign you. 💯

**Comment by Ryan-Maddock-96** [comment]
I have checked just needs a bit of js to remove an inline style when you close the popup

**Comment by SyedImtiyaz-1** [comment]
Fix and attach a video in your PR.

**Comment by Ryan-Maddock-96** [comment]
Fixed and video attached 👍

**Comment by SyedImtiyaz-1** [comment]
Great Work @Ryan-Maddock-96

**Comment by SyedImtiyaz-1** [comment]
Here is the issue : 
[Screencast from 02-10-23 12:28:20 PM IST.webm](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/121503426/47b30865-c2be-408d-98c0-e87928374909)

**Comment by SyedImtiyaz-1** [comment]
I have Fixed... the mentioned issue thanks @Ryan-Maddock-96 for your contribution.
