### ISSUE TITLE
Add a Feature 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/PreciousServices-#26]
Hello Contributors,
I want to add one feature in this project in projects page.

### Feature Details : 
If user buyed the project then user must able to see their downloaded project after login to their perticular account.

![image](https://github.com/SyedImtiyaz-1/PreciousServices/assets/121503426/3b3f15ce-2648-4bee-9c62-2753e19d861a)

- If payment done then, project must be save in their logined account.

Feel free to ask question regarding the issue!!!

**Comment by satprakash-1** [comment]
can you assign this issue to me

**Comment by SyedImtiyaz-1** [comment]
Sure @satprakash-1 ,
Please add Screenshot/Video in the PR too.

**Comment by satprakash-1** [comment]
ok

**Comment by SyedImtiyaz-1** [comment]
@satprakash-1  any updates ?

**Comment by satprakash-1** [comment]
still working on the feature...surely I will give update tomorrow

**Comment by satprakash-1** [comment]
@SyedImtiyaz-1  I am facing and issue?

**Comment by SyedImtiyaz-1** [comment]
which issue ?

**Comment by SyedImtiyaz-1** [comment]
which issue ?
