### ISSUE TITLE
OurTeam Page is missing : #team.html

### ISSUE THREAD

**Issue by Ank61** [SyedImtiyaz-1/PreciousServices-#30]
Hello Everyone, 

It seems like 'ourTeam' page is not connected to any section of the main page. I am working on the issue as of now. @SyedImtiyaz-1  can you please assign this issue to me.

Thank you

**Comment by Ank61** [comment]
Thanks @SyedImtiyaz-1 , will let you know when I am done!

**Comment by anto-mervin** [comment]
I can fix this problem
