### ISSUE TITLE
[BUG]: Sticky Navbar not working properly in careers page

### ISSUE THREAD

**Issue by Saifullah00** [SyedImtiyaz-1/PreciousServices-#38]
**Describe the bug**
When we are trying to scroll the careers page in Mobile or in responsive mode, the navbar is not sticked properly.

**To Reproduce**
1. Go to 'https://preciousitservices.vercel.app/index.html'
2. Click on ''Carrers section '
3. Scroll down to 

https://github.com/SyedImtiyaz-1/PreciousServices/assets/78204201/3c8e8f16-3881-4eff-805a-4b13cc282b21

**Expected behavior**
Navbar should stick properly with proper background colour.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ✓] I have checked the existing issues
- [✓ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ✓] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [ ✓] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by rayyyyofsunshine** [comment]
Is this already assigned?

**Comment by Saifullah00** [comment]
> Is this already assigned?

Yes, I'm working on it.
