### ISSUE TITLE
[BUG]:  Remove Node Modules from the root of the Repo

### ISSUE THREAD

**Issue by Prasundas99** [SyedImtiyaz-1/PreciousServices-#51]
**Describe the bug**
This repo carries node modules  which should not be here as it might take up a lot of time to commit and also these can be generated by every developers too

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [X] I have checked the existing issues
- [X]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by subhasis003** [comment]
please assign it to me @Prasundas99

**Comment by Prasundas99** [comment]
@SyedImtiyaz-1
