### ISSUE TITLE
[feat]: Login button

### ISSUE THREAD

**Issue by Parvezkhan0** [SyedImtiyaz-1/PreciousServices-#63]
**Describe the bug**
The button says "Login" instead it should display "Log In"
**To Reproduce**
1. Go to "https://preciousitservices.vercel.app/"
2. On the top- right of Navigation bar. 
3. See the button which says "Login"

**Expected behavior**
The button says "Login" instead it should display "Log In"

**Screenshots**

<img width="449" alt="image" src="https://github.com/SyedImtiyaz-1/PreciousServices-/assets/137421089/83c1ee83-4df3-4da0-82ce-632ec6658915">

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x ] I have checked the existing issues
- [ x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [ x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by Parvezkhan0** [comment]
I want to work on this issue. Please assgin it to me

**Comment by Nikhil743** [comment]
I want to work on this issue for hacktoberfest. Please assgin it to me
