### ISSUE TITLE
[BUG]: Contact form submit button not centered

### ISSUE THREAD

**Issue by arnabpal2022** [SyedImtiyaz-1/PreciousServices-#69]
**Describe the bug**
1. Submit Button isn't Positioned in Center.

**To Reproduce**
1. Go to preciousitservices.vercel.app
2. Click on Contact
4. See the Button not in Middle.

**Expected behavior**
Positioned in Center will make it more visually corrected

**Screenshots**
![image](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/116568728/d14a576d-f8c3-497a-8696-4db2d1ddc9b3)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ] I have checked the existing issues
- [ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by arnabpal2022** [comment]
I want to work on this issue, can I do it?

**Comment by Karamraj** [comment]
I want to work on this issue

**Comment by YourOwnItsMeDHC** [comment]
I have solved these issue, please assign it to me, I will fix it.

**Comment by SyedImtiyaz-1** [comment]
### This issue is fixed now. I'm Closing this
