### ISSUE TITLE
[ui-upgrade]: UI Enhancement in the form section

### ISSUE THREAD

**Issue by premsaivarmachekuri** [SyedImtiyaz-1/PreciousServices-#72]
# UI Upgrade Issue

## Description
The current UI layout has a bug where the map and the form elements are vertically aligned, which results in poor visibility and a compressed appearance of the map at the top of the form.

## To Reproduce
1. Go to the application.
2. Navigate to the submit form section.
3. Observe the vertical alignment of the map and form elements.

## Expected Behavior

The expected behavior is to enhance the UI layout by aligning the map and the form elements horizontally. This horizontal alignment will address the following:

- **Improved Visibility**: Aligning the map and the form elements horizontally will provide a more visible and accessible map interface for users, ensuring they can interact with it without any hindrance.

- **Optimized Space**: The horizontal arrangement will make better use of the screen space, resulting in a cleaner and more organized UI.

## Screenshots
![image](https://github.com/SyedImtiyaz-1/PreciousServices-/assets/110842297/43604f7f-af26-41ab-8b41-81e607e5674f)

## Additional Context
I have experience in bringing wealth of experience in addressing issues like this one and enhancing the overall user experience in various projects. Over the years, I've successfully tackled similar challenges by aligning user interface elements for improved visibility and usability. My commitment to enhancing user satisfaction through thoughtful design improvements has been a consistent part of my contributions to different projects.
## 🌟 Note
Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues.
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Have you added your name in [CONTRIBUTING.md](https://github.com/SyedImtiyaz-1/PreciousServices/blob/main/CONTRIBUTING.md)
- [x] I want to work on this issue.

**Comment by VIDYA1980** [comment]
i want to work on this issue

**Comment by vivekBoii** [comment]
like this
[https://drive.google.com/file/d/18zBb0L2oiunnTioUPHTwUUwzdOPIC1mP/view?usp=sharing](url)

**Comment by vivekBoii** [comment]
like this
https://github.com/SyedImtiyaz-1/PreciousServices-/issues/url

**Comment by vivekBoii** [comment]
like this
https://drive.google.com/file/d/18zBb0L2oiunnTioUPHTwUUwzdOPIC1mP/view?usp=sharing
